### ISSUE TITLE
Twig namespaces support

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/plugin-php-data-inheritance#2]
The plugin does not seem to work with namespace includes e.g. `@atoms/pattern/path.twig`.

**Comment by dmolsen** [comment]
@aleksip -

Does lineage work at all when using namespaces? The lineage regex will find your example but I don't think it can make a connection to an existing pattern to build the lineage list on the front-end. It's probably a deeper "problem" than just this plugin.

**Comment by nstriedinger** [comment]
Pardon, I think I posted this in the wrong place. Here's my issue:

In Patternlab all my includes have been changed to twig template namespaces and now there is no lineage link `The <strong>{{ patternName }}</strong> pattern contains the following patterns:`

Is this a feature request?

**Comment by aleksip** [comment]
Closing as this now works since Twig PatternEngine v2.1.3.
