### ISSUE TITLE
Documentation on using with pseudo selectors.

### ISSUE THREAD

**Issue by thiagodemellobueno** [pattern-lab/plugin-php-data-inheritance#4]
Here: http://patternlab.io/docs/pattern-pseudo-patterns.html
They suggest using these plugins to using pseudo patterns as includes.
But it doesn't seem to be that straightforward... perhaps an example?

**Comment by froboy** [comment]
@thiagodemellobueno I'm interested to know if you found some documentation on this? I'd love to see it.
